/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiSyncRouteImport } from './routes/api.sync'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthWhoopRouteImport } from './routes/api.auth.whoop'
import { Route as ApiAuthWhoopCallbackRouteImport } from './routes/api.auth.whoop.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWhoopRoute = ApiAuthWhoopRouteImport.update({
  id: '/api/auth/whoop',
  path: '/api/auth/whoop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWhoopCallbackRoute = ApiAuthWhoopCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthWhoopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoop': typeof ApiAuthWhoopRouteWithChildren
  '/api/auth/whoop/callback': typeof ApiAuthWhoopCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoop': typeof ApiAuthWhoopRouteWithChildren
  '/api/auth/whoop/callback': typeof ApiAuthWhoopCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoop': typeof ApiAuthWhoopRouteWithChildren
  '/api/auth/whoop/callback': typeof ApiAuthWhoopCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/dashboard'
    | '/api/mcp'
    | '/api/sync'
    | '/api/auth/logout'
    | '/api/auth/whoop'
    | '/api/auth/whoop/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/dashboard'
    | '/api/mcp'
    | '/api/sync'
    | '/api/auth/logout'
    | '/api/auth/whoop'
    | '/api/auth/whoop/callback'
  id:
    | '__root__'
    | '/'
    | '/api/dashboard'
    | '/api/mcp'
    | '/api/sync'
    | '/api/auth/logout'
    | '/api/auth/whoop'
    | '/api/auth/whoop/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthWhoopRoute: typeof ApiAuthWhoopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/whoop': {
      id: '/api/auth/whoop'
      path: '/api/auth/whoop'
      fullPath: '/api/auth/whoop'
      preLoaderRoute: typeof ApiAuthWhoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/whoop/callback': {
      id: '/api/auth/whoop/callback'
      path: '/callback'
      fullPath: '/api/auth/whoop/callback'
      preLoaderRoute: typeof ApiAuthWhoopCallbackRouteImport
      parentRoute: typeof ApiAuthWhoopRoute
    }
  }
}

interface ApiAuthWhoopRouteChildren {
  ApiAuthWhoopCallbackRoute: typeof ApiAuthWhoopCallbackRoute
}

const ApiAuthWhoopRouteChildren: ApiAuthWhoopRouteChildren = {
  ApiAuthWhoopCallbackRoute: ApiAuthWhoopCallbackRoute,
}

const ApiAuthWhoopRouteWithChildren = ApiAuthWhoopRoute._addFileChildren(
  ApiAuthWhoopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthWhoopRoute: ApiAuthWhoopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
